# Generated by Django 5.0.1 on 2024-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_number', models.IntegerField(max_length=10)),
                ('bus_rotues', models.CharField(max_length=50)),
                ('bus_fare', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='indian',
        ),
    ]
