# Generated by Django 5.0.1 on 2024-01-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bus_details_delete_indian'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_details',
            name='bus_timmigs',
            field=models.DateTimeField(blank=True, default='2006-10-25 14:30:59'),
        ),
    ]
