# Generated by Django 5.0.1 on 2024-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_bus_details_bus_timmigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_details',
            name='bus_timmigs',
            field=models.DateTimeField(blank=True),
        ),
    ]
