# Generated by Django 5.0.1 on 2024-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_bus_details_bus_timmigs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_details',
            name='bus_timmigs',
        ),
        migrations.AddField(
            model_name='bus_details',
            name='bus_Start_timmigs',
            field=models.DateTimeField(blank=True, default='2006-12-27 10:20:50'),
        ),
        migrations.AddField(
            model_name='bus_details',
            name='bus_end_timmigs',
            field=models.DateTimeField(blank=True, default='2006-12-27 16:30:10'),
        ),
        migrations.AlterField(
            model_name='bus_details',
            name='bus_fare',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus_details',
            name='bus_number',
            field=models.IntegerField(),
        ),
    ]
